FROM node:20.12.0-alpine3.19

WORKDIR /use/src/app

COPY package.json package-lock.json turbo.json tsconfig.json ./
COPY apps/bank-webhook ./apps/bank-webhook
COPY apps/user-app ./apps/user-app
COPY packages ./packages


# Install dependencies
RUN npm install
# Added command for db:generate in global package.json
RUN npm run db:generate

RUN npm run build

CMD [ "npm", "run", "start-app" ]