import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Provider } from "./provider";
import { AppbarClient } from "./components/AppbarClient";
import { getServerSession } from "next-auth";
import { redirect } from "next/navigation";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Turborepo",
  description: "Generated by create turbo",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {


  const session  = await getServerSession();
  if(!session?.user){
    redirect("/api/auth/signin")
  }

  return (
    <html lang="en">
      <Provider>
        <body className={inter.className}>
          <AppbarClient />
          {children}
        </body>
      </Provider>
    </html>
  );
}
