import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Provider } from "./provider";
import { AppbarClient } from "./components/AppbarClient";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Turborepo",
  description: "Generated by create turbo",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  // const session  = await getServerSession();
  // if(!session?.user){
  //   redirect("/home")
  // }
  return (
    <html lang="en">
      <Provider>
        <body className={inter.className}>
          <AppbarClient />
          <div className="mt-[7vh]">
          {children}
          </div>
        </body>
      </Provider>
    </html>
  );
}
